FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV APP_VERSION=v1.0.0
ENV APP_COLOR=#4F46E5
ENV APP_COLOR_NAME=indigo

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "-w", "1", "--access-logfile", "-", "app:app"]
